import Card from '../types/card'

const mockCards: Card[] = [
  {
    title: 'Designing and implementing UI components',
    // razumem da bi ovde idealno bio neki date objekat ali sam odlucio da za ovaj primer koristim string
    dueDate: 'Jan 3,',
    messages: null,
    subtasks: null,
    // ovde bi idealno bio array user objekata osoba kojima je dodeljen ovaj task, ja sam za ovaj primer odlucio da idem sa listom avatar slicica
    avatars: null,
    // kao i ranije bilo mi je lakse da napravim jedan boolean i dodam par labela samo da pokazem kako bi oni bili renderovani
    labels: false,
    priority: false,
    // ovde sam razmisljao kako bih sortirao kartice odnosno taskove po tome kojoj koloni pripadaju,
    // odabrao sam da samo napravim par boolean propertija jer mi je bez dodatnog konteksta to bilo najlakse
    // naravno razumem da bi se za produkciju ovakav pristup morao promeniti
    toDo: true,
    inProgress: false,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title: 'Creating and implementing design system components',
    dueDate: 'May 8. - Sep 10.',
    messages: 7,
    subtasks: 2,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: false,
    priority: false,
    toDo: true,
    inProgress: false,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title: 'Implementing UI animations and transitions',
    dueDate: null,
    messages: null,
    subtasks: null,
    avatars: null,
    labels: false,
    priority: false,
    toDo: true,
    inProgress: false,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title: 'Developing and integrating UI libraries and frameworks',
    dueDate: 'May 8. - Sep 10.',
    messages: 7,
    subtasks: 2,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: true,
    priority: false,
    toDo: true,
    inProgress: false,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title: 'Designing and implementing user flows and interactions',
    dueDate: 'May 8. - Sep 10.',
    messages: 7,
    subtasks: 2,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: true,
    priority: false,
    toDo: true,
    inProgress: false,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title: 'Building and integrating UI kits, Implementing responsive design',
    dueDate: 'May 8. - Sep 10.',
    messages: null,
    subtasks: 2,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: true,
    priority: false,
    toDo: false,
    inProgress: true,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title:
      'Implementing UI localization and internationalization, Implementing re…',
    dueDate: null,
    messages: null,
    subtasks: 2,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: true,
    priority: false,
    toDo: false,
    inProgress: true,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title: 'Creating wireframes and mockups',
    dueDate: null,
    messages: null,
    subtasks: null,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: false,
    priority: false,
    toDo: false,
    inProgress: true,
    forReview: false,
    testing: false,
    done: false,
  },
  {
    title: 'Ensuring UI consistency across different platforms and devices',
    dueDate: 'May 8. - Sep 10. 2019',
    messages: null,
    subtasks: null,
    avatars: null,
    labels: true,
    priority: false,
    toDo: false,
    inProgress: false,
    forReview: true,
    testing: false,
    done: false,
  },
  {
    title: 'Creating and implementing UI guidelines and best practices',
    dueDate: 'May 8.',
    messages: null,
    subtasks: null,
    avatars: null,
    labels: false,
    priority: true,
    toDo: false,
    inProgress: false,
    forReview: true,
    testing: false,
    done: false,
  },
  {
    title: 'Developing and integrating UI icons and images',
    dueDate: null,
    messages: null,
    subtasks: null,
    avatars: null,
    labels: false,
    priority: false,
    toDo: false,
    inProgress: false,
    forReview: true,
    testing: false,
    done: false,
  },
  {
    title: 'Creating and implementing UI tests',
    dueDate: 'May 8. - Sep 10.',
    messages: 7,
    subtasks: 2,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: true,
    priority: false,
    toDo: false,
    inProgress: false,
    forReview: false,
    testing: true,
    done: false,
  },
  {
    title: 'Developing and integrating UI forms and validation',
    dueDate: 'May 8. - Sep 10.',
    messages: null,
    subtasks: 2,
    avatars: [
      'https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png',
    ],
    labels: false,
    priority: false,
    toDo: false,
    inProgress: false,
    forReview: false,
    testing: false,
    done: true,
  },
  {
    title: 'Creating and implementing UI patterns for the page',
    dueDate: null,
    messages: null,
    subtasks: null,
    avatars: null,
    labels: false,
    priority: false,
    toDo: false,
    inProgress: false,
    forReview: false,
    testing: false,
    done: true,
  },
]

export default mockCards
// https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png
